#!/usr/bin/env bash
#MISE description="Build, watch, and serve the website locally"
exec npx --no-install esbuild src/index.tsx --bundle --format=iife --target=es2022 --loader:.css=text --sourcemap --outfile=public/dist/bundle.js --servedir=public --serve=localhost:8000 --watch
